const range=(from,to)=>Array.from({length:to-from+1},(_,i)=>from+i);
const groups={
  exhibition:{title:'展厅会展',en:'EXHIBITION',pages:range(4,30),projects:[['红十字生命安全体验馆','生命线 · 安全体验',5],['新星市智慧城市运营中心','未来数据 · 智慧城市',11],['2025农博会 · 渔业互保','海洋产业 · 互助保障',18],['2025农博会 · 主题馆','农业未来 · 主题叙事',25]]},
  'public-art':{title:'公共艺术',en:'PUBLIC ART',pages:range(31,63),projects:[['杭州电竞中心','亚运电竞 · AR交互',32],['临平区亚运氛围营造','城市记忆 · 亚运文化',38],['桐庐未来湖公园','水墨山水 · 诗意雕塑',45],['太平鸟30周年园区氛围','品牌记忆 · 羽翼符号',51],['西湖东坡','宋韵诗词 · 空间错位',55],['武汉江汉经济开发区','时空通道 · 科技人文',59]]},
  personal:{title:'个人创作',en:'PERSONAL CREATION',pages:range(64,95),projects:[['AI','AI协同 · 视觉至应用',65],['产品渲染','真实材质 · 光影叙事',71],['荣誉奖杯','荣誉象征 · 结构语言',76],['艺术作品','抽象感知 · 材料实验',83],['IP设计','角色叙事 · 品牌个性',89],['CG场景','虚拟场景 · 氛围构建',92]]}
};
const order=Object.keys(groups),requested=new URLSearchParams(location.search).get('project');
const key=requested in groups?requested:'exhibition',data=groups[key],reader=document.querySelector('#reader'),counter=document.querySelector('#counter'),links=document.querySelector('#project-links');
const num=n=>String(n).padStart(3,'0'),storageKey='zhang-tao-reader-positions-v3';
const readPositions=()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}};
const writePosition=()=>{const positions=readPositions();positions[key]=reader.scrollTop;localStorage.setItem(storageKey,JSON.stringify(positions))};
document.title=`张涛｜${data.title}`;
const imageSlides=data.pages.map((page,index)=>`<section class="spread" data-index="${index}" data-page="${page}"><img src="assets/pages/${num(page)}.jpg" alt="${data.title}第${page}页" decoding="async"${index<3?' fetchpriority="high"':''}><small>${String(index+1).padStart(2,'0')} / ${String(data.pages.length).padStart(2,'0')}</small></section>`).join('');
const otherChapters=order.filter(name=>name!==key).map(name=>`<a href="project.html?project=${name}" data-click>${groups[name].title}<small>${groups[name].en}</small></a>`).join('');
const chapterEnd=`<section class="spread chapter-end" data-index="${data.pages.length}" data-terminal="true"><p>CHAPTER COMPLETE</p><h1>${data.title}</h1><div class="chapter-links">${otherChapters}</div><small class="continue-note">继续向下翻阅，进入下一章节</small></section>`;
reader.innerHTML=imageSlides+chapterEnd;
links.innerHTML=data.projects.map(([title,theme,page])=>`<button type="button" data-page="${page}" data-click><strong>${title}</strong><small>${theme}</small></button>`).join('');
const spreads=[...reader.querySelectorAll('.spread')];let activeIndex=0,horizontalLock=false;
function prefetch(index){for(let i=Math.max(0,index-2);i<=Math.min(data.pages.length-1,index+9);i++){const image=new Image();image.src=`assets/pages/${num(data.pages[i])}.jpg`;image.decode?.().catch(()=>{})}}
function update(index){activeIndex=Math.max(0,Math.min(index,spreads.length-1));const currentPage=data.pages[Math.min(activeIndex,data.pages.length-1)];counter.textContent=`${String(Math.min(activeIndex+1,data.pages.length)).padStart(2,'0')} / ${String(data.pages.length).padStart(2,'0')}`;spreads.forEach((spread,i)=>spread.classList.toggle('active',i===activeIndex));let current=0;data.projects.forEach((project,i)=>{if(currentPage>=project[2])current=i});links.querySelectorAll('button').forEach((button,i)=>button.classList.toggle('active',i===current));prefetch(activeIndex)}
function jumpToPage(page){const index=data.pages.indexOf(page);if(index>=0)spreads[index].scrollIntoView({behavior:'smooth',block:'start'})}
function changeChapter(direction){if(horizontalLock)return;horizontalLock=true;writePosition();setTimeout(()=>horizontalLock=false,700);const nextIndex=order.indexOf(key)+direction;if(nextIndex<0){location.href='index.html#home';return}if(nextIndex>=order.length){location.href='index.html#contact';return}location.href=`project.html?project=${order[nextIndex]}`}
links.addEventListener('click',event=>{const button=event.target.closest('button[data-page]');if(button)jumpToPage(+button.dataset.page)});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)update(+entry.target.dataset.index)}),{root:reader,threshold:.64});spreads.forEach(spread=>observer.observe(spread));
document.querySelector('#previous').onclick=()=>reader.scrollBy({top:-innerHeight,behavior:'smooth'});document.querySelector('#next').onclick=()=>reader.scrollBy({top:innerHeight,behavior:'smooth'});document.querySelector('#chapter-previous').onclick=()=>changeChapter(-1);document.querySelector('#chapter-next').onclick=()=>changeChapter(1);
reader.addEventListener('scroll',()=>{clearTimeout(reader._saveTimer);reader._saveTimer=setTimeout(writePosition,160)},{passive:true});
reader.addEventListener('wheel',event=>{if(Math.abs(event.deltaX)>Math.abs(event.deltaY)*1.25&&Math.abs(event.deltaX)>20){event.preventDefault();changeChapter(event.deltaX>0?1:-1)}else if(activeIndex===spreads.length-1&&event.deltaY>18)changeChapter(1)},{passive:false});
let touchStart,pointerStart;reader.addEventListener('touchstart',event=>touchStart={x:event.touches[0].clientX,y:event.touches[0].clientY},{passive:true});reader.addEventListener('touchend',event=>{if(!touchStart)return;const dx=event.changedTouches[0].clientX-touchStart.x,dy=event.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>58&&Math.abs(dx)>Math.abs(dy)*1.2)changeChapter(dx<0?1:-1);else if(activeIndex===spreads.length-1&&touchStart.y-event.changedTouches[0].clientY>48)changeChapter(1)},{passive:true});reader.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&!event.target.closest('a,button'))pointerStart={x:event.clientX,y:event.clientY}});reader.addEventListener('pointerup',event=>{if(!pointerStart)return;const dx=event.clientX-pointerStart.x,dy=event.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.2)changeChapter(dx<0?1:-1)});
addEventListener('pagehide',writePosition);const saved=readPositions()[key];requestAnimationFrame(()=>{if(saved>0)reader.scrollTop=saved;update(Math.round(reader.scrollTop/Math.max(innerHeight,1)));prefetch(activeIndex)});
