const canvas=document.querySelector('#sand');
const ctx=canvas.getContext('2d');
let W,H,particles=[],soundOn=false,audio,lastSpawn=0;
const mouse={x:-9999,y:-9999,active:false};
const particleCount=()=>Math.min(2000,Math.max(1088,Math.floor(innerWidth*innerHeight/780)));
function makeParticle(x=Math.random()*innerWidth,y=Math.random()*innerHeight,soft=false){return{x,y,vx:(Math.random()-.5)*.133,vy:(Math.random()-.5)*.133,s:Math.random()*1.7+.28,phase:Math.random()*6.28,alpha:soft?0:1,dissolve:false}}
function fit(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const count=particleCount();if(!particles.length)particles=Array.from({length:count},()=>makeParticle());else if(particles.length<count)while(particles.length<count)particles.push(makeParticle());else particles.length=count}
function dissolveAndSpawn(){for(let i=0;i<3;i++){let retiring=particles[(Math.random()*particles.length)|0];for(let attempt=0;attempt<6&&retiring.dissolve;attempt++)retiring=particles[(Math.random()*particles.length)|0];retiring.dissolve=true;let born=particles[(Math.random()*particles.length)|0];for(let attempt=0;attempt<6&&born===retiring;attempt++)born=particles[(Math.random()*particles.length)|0];Object.assign(born,makeParticle(mouse.x+(Math.random()-.5)*28,mouse.y+(Math.random()-.5)*28,true))}}
function bounceParticles(){const cell=18,grid=new Map();particles.forEach((p,index)=>{const key=`${Math.floor(p.x/cell)},${Math.floor(p.y/cell)}`,list=grid.get(key);if(list)list.push(index);else grid.set(key,[index])});for(let i=0;i<particles.length;i++){const p=particles[i],cx=Math.floor(p.x/cell),cy=Math.floor(p.y/cell);for(let x=cx-1;x<=cx+1;x++)for(let y=cy-1;y<=cy+1;y++){const nearby=grid.get(`${x},${y}`);if(!nearby)continue;for(const j of nearby){if(j<=i)continue;const q=particles[j],dx=q.x-p.x,dy=q.y-p.y,dist=Math.hypot(dx,dy)||.001,min=(p.s+q.s)*1.65+1.1;if(dist>=min)continue;const nx=dx/dist,ny=dy/dist,overlap=(min-dist)*.5;p.x-=nx*overlap;p.y-=ny*overlap;q.x+=nx*overlap;q.y+=ny*overlap;const closing=(q.vx-p.vx)*nx+(q.vy-p.vy)*ny;if(closing<0){p.vx+=nx*closing;p.vy+=ny*closing;q.vx-=nx*closing;q.vy-=ny*closing}}}}}
function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);if(mouse.active&&t-lastSpawn>48){dissolveAndSpawn();lastSpawn=t}for(const p of particles){const dx=p.x-mouse.x,dy=p.y-mouse.y,d=Math.hypot(dx,dy)||1;if(mouse.active&&d<220){const f=(1-d/220)*.126;p.vx+=dx/d*f;p.vy+=dy/d*f}p.vx+=Math.sin(t*.00031+p.phase)*.0019;p.vy+=Math.cos(t*.00024+p.phase)*.00175;p.vx*=.979;p.vy*=.979;p.x+=p.vx;p.y+=p.vy;if(p.x<0){p.x=0;p.vx=Math.abs(p.vx)}else if(p.x>innerWidth){p.x=innerWidth;p.vx=-Math.abs(p.vx)}if(p.y<0){p.y=0;p.vy=Math.abs(p.vy)}else if(p.y>innerHeight){p.y=innerHeight;p.vy=-Math.abs(p.vy)}if(p.dissolve){p.alpha-=.035;if(p.alpha<=.04)Object.assign(p,makeParticle())}else p.alpha=Math.min(1,p.alpha+.05)}bounceParticles();for(const p of particles){ctx.fillStyle=`rgba(247,249,250,${(.27+Math.sin(t*.0011+p.phase)*.11)*p.alpha})`;ctx.fillRect(p.x,p.y,p.s,p.s)}requestAnimationFrame(draw)}
fit();addEventListener('resize',fit);addEventListener('pointermove',event=>{mouse.x=event.clientX;mouse.y=event.clientY;mouse.active=true});addEventListener('pointerleave',()=>{mouse.active=false});requestAnimationFrame(draw);
function clickSound(){if(!soundOn)return;audio??=new(window.AudioContext||window.webkitAudioContext)();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(440,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(180,audio.currentTime+.09);gain.gain.setValueAtTime(.018,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.11)}
document.querySelector('[data-sound]').addEventListener('click',event=>{soundOn=!soundOn;event.currentTarget.setAttribute('aria-pressed',soundOn);clickSound()});document.querySelectorAll('[data-click]').forEach(item=>item.addEventListener('click',clickSound));const reveals=document.querySelectorAll('.reveal');const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('in')}),{threshold:.18});reveals.forEach(item=>io.observe(item));if(location.hash){requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({block:'start'}));}
